WITH CTE AS (
SELECT

TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) As DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) As HOUR_STARTED_AT,
{{day_type('STARTED_AT')}} AS DAY_TYPE,
{{get_season('STARTED_AT')}} AS SEASON_OF_YEAR

  FROM
{{source('demo','bike')}}
WHERE STARTED_AT != 'started_at'
)

SELECT * FROM CTE