WITH TRIPS AS 
(

Select 
RIDE_ID,
RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
START_STATIO_ID AS START_STATTION_ID,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND,(ENDED_AT),TO_TIMESTAMP(STARTED_AT)) as TRIP_DURATION_SECONDS
from {{source('demo','bike')}}
WHERE RIDE_ID != 'ride_id'


)

Select * from TRIPS